### ISSUE TITLE
Review of Nate's pseudocode

### ISSUE THREAD

**Issue by bwinnacott** [2020-bgmp/demultiplexing-ndeimler99#3]
[Nate_pseudo.pdf](https://github.com/2020-bgmp/demultiplexing-ndeimler99/files/5013277/Nate_pseudo.pdf)

**Comment by bwinnacott** [comment]
Reach out if you have any questions regarding my comments!

**Comment by ndeimler99** [comment]
Thanks for the comments they were super helpful.  I wrote the pseudocode and decided to change the ways I was doing a few things and probably never fixed said changes further down in the code.  good catch!
