### ISSUE TITLE
Pseudo Code Peer Review

### ISSUE THREAD

**Issue by monicangelic** [2020-bgmp/demultiplexing-ndeimler99#4]
Logistics:
-Yes, the algorithm makes sense and the logic is easy to follow. I like how everything was tabbed as if it were the actual python code.
-All of the functions were listed out in an order that makes sense as well. 

Algorithm:
-The algorithm is written to do everything it’s supposed to do and there are only a few things to consider:
-In your rev_complement() function, it would be a good idea to add in ‘replace N with N’, because we know that these files do contain N’s within them
- Also within this function, I would state how you are going to get the reverse complement of the sequence (I know you are going to go in depth in your actual code for this - but it’s good to specify this beforehand). 

-I like that you have a function to open and close your files- but I didn’t see anywhere in those functions that mentions how you are going to name the files 
-A suggestion for your parse_files() function: use a numpy 1D array. I think that would be more time effective

Code:
-All of the functions are reasonable and are able to standalone as pieces of code. I appreciated the extreme depth and thought of this pseudo code! Everything seems to talk to one another. I think this will turn out well and with minor tweaks, it will be very effective code :)

**Comment by ndeimler99** [comment]
Thank you so much! I did not even think about the N problem.  I might only call this function after I determined if there is an N or not in the sequence (if there is an N we do not care what the rev complement is).  But if I do it another way I will definitely have to add that. Good catch!
