### ISSUE TITLE
Make dict outside fxn

### ISSUE THREAD

**Issue by Leslie-C** [2020-bgmp/demultiplexing-ndeimler99#5]
https://github.com/2020-bgmp/demultiplexing-ndeimler99/blob/48ac1dbd3c3da6cb6017665b28342e7a777f7e4e/demultiplex.py#L28

If you make this dictionary outside your function, you'll get a small speedup.

**Comment by ndeimler99** [comment]
dictionary was moved outside the function so that the dictionary is created once and stored in memory rather than recreating it each time the function is called
